---
- name: my test playbook
  hosts: webservers
  become: true
  tasks:
  -  name: stop httpd service
     service:
       name: httpd
       state: stopped

  -  name: uninstalled httpd service
     yum:
       name: httpd
       state: removed



